;************** TRABALHIN ZIKA (help) GGEZ *****************
LIST   P=PIC16F628A
RADIX DEC	
#INCLUDE <P16F628A.INC>
	__CONFIG H'3F10'

	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMÓRIA DE
					;USUÁRIO
	CONTADOR1
	CONTADOR2
	CONTADOR3

	ENDC			;FIM DO BLOCO DE MEMÓRIA	

	#DEFINE	BOTAO PORTA,2 ;PORTA DO BOTÃO
					  ; 0 -> PRESSIONADO
					  ; 1 -> LIBERADO

	#DEFINE	TERREO PORTB,0	;PORTA DO LED TERREO
					; 0 -> APAGADO
					; 1 -> ACESO	

	#DEFINE	PRIMEIRO PORTB,1	;PORTA DO LED PRIMEIRO ANDAR
					; 0 -> APAGADO
					; 1 -> ACESO	

	#DEFINE	SEGUNDO	PORTB,2	;PORTA DO LED SEGUNDO ANDAR
					; 0 -> APAGADO
					; 1 -> ACESO	

	#DEFINE	TERCEIRO PORTB,3	;PORTA DO LED TERCEIRO ANDAR
					; 0 -> APAGADO
					; 1 -> ACESO	

	#DEFINE	QUARTO PORTB,4	;PORTA DO LED QUARTO ANDAR
					; 0 -> APAGADO
					; 1 -> ACESO	

	#DEFINE	CONTROLE PORTB,5 ;PORTA DO LED CONTROLE
					; 0 -> APAGADO
					; 1 -> ACESO	
	
	ORG	0x00		;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
		
INICIO
	CLRF	PORTA		;LIMPA O PORTA
	CLRF	PORTB		;LIMPA O PORTB
	BSF STATUS, RP0			;ALTERA PARA O BANCO 1
	MOVLW	B'00000100'
	MOVWF	TRISA		;DEFINE RA2 COMO ENTRADA E DEMAIS COMO SAÍDAS
	CLRF	TRISB		;DEFINE TODO O PORTB COMO SAÍDA
	CLRF	INTCON		;TODAS AS INTERRUPÇÕES DESLIGADAS
	BCF STATUS, RP0 ;RETORNA PARA O BANCO 0
	MOVLW	B'00000111'
	MOVWF	CMCON		;DEFINE O MODO DO COMPARADOR ANALÓGICO

REPETE
	CALL TER
	NOP
	CALL PRIMEIROANDAR
	NOP
	CALL SEGUNDOANDAR
	NOP
	CALL TERCEIROANDAR
	NOP
	CALL QUARTOANDAR
	NOP
	CALL TERCEIROANDAR
	NOP
	CALL SEGUNDOANDAR
	NOP
	CALL PRIMEIROANDAR
	NOP
	CALL TER
	GOTO REPETE ;DELAY DE 1S

TER
	BSF TERREO
	BSF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERREO
	BSF CONTROLE
	RETURN

PRIMEIROANDAR
	BSF PRIMEIRO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF PRIMEIRO
	BSF CONTROLE
	BSF PRIMEIRO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF PRIMEIRO
	BSF CONTROLE
	RETURN

SEGUNDOANDAR
	BSF SEGUNDO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF SEGUNDO
	BSF CONTROLE
	BSF SEGUNDO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF SEGUNDO
	BSF CONTROLE
	BSF SEGUNDO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF SEGUNDO
	BSF CONTROLE
	RETURN

TERCEIROANDAR
	BSF TERCEIRO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERCEIRO
	BSF CONTROLE
	BSF TERCEIRO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERCEIRO
	BSF CONTROLE
	BSF TERCEIRO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERCEIRO
	BSF CONTROLE
	BSF TERCEIRO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERCEIRO
	BSF CONTROLE
	RETURN

QUARTOANDAR
	BSF QUARTO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF QUARTO
	BSF CONTROLE
	BSF QUARTO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF QUARTO
	BSF CONTROLE
	BSF QUARTO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF QUARTO
	BSF CONTROLE
	BSF QUARTO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF QUARTO
	BSF CONTROLE
	BSF QUARTO
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF QUARTO
	BSF CONTROLE
	RETURN
	
PRESSIONADO
	BSF TERREO
	BSF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERREO
	BSF CONTROLE
	BSF TERREO
	BSF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERREO
	BSF CONTROLE
	BSF TERREO
	BSF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERREO
	BSF CONTROLE
	BSF TERREO
	BSF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERREO
	BSF CONTROLE
	BSF TERREO
	BSF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF CONTROLE
	CALL ATRASO ;DELAY DE 1S
	BCF TERREO
	BSF CONTROLE
	RETURN

ATRASO			
	;SETAR CONTADORES	
	MOVLW	7
	MOVWF	CONTADOR1
	MOVLW	22 
	MOVWF	CONTADOR2
	MOVLW   67 
	MOVWF	CONTADOR3

ATRASO1				
	DECFSZ	CONTADOR1 ;TESTAR SE CONTADOR1 < 0
	GOTO ATRASO2
	NOP ;NOP SÓ PRA DAR UM MIGUÉ
	RETURN ;RETORNAR PARA ONDE O ATRASO FOI CHAMADO
ATRASO2
	DECFSZ CONTADOR2 ;TESTAR SE CONTADOR1 < 0
	GOTO ATRASO3
	GOTO ATRASO1
ATRASO3
	DECFSZ CONTADOR3 ;TESTAR SE CONTADOR1 < 0
	GOTO ATRASO3
	GOTO ATRASO2	
END